# Generated by Django 3.2.20 on 2023-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
    ]
