# Generated by Django 3.2.20 on 2023-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(max_length=7, verbose_name='RG'),
        ),
    ]
