# Generated by Django 3.2.20 on 2023-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20230719_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rg',
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=14, unique=True, verbose_name='Telefone'),
        ),
    ]
