# Generated by Django 3.2.20 on 2023-07-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
