# Generated by Django 3.2.20 on 2023-07-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_student_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/%Y/%m/%d', verbose_name='Foto'),
        ),
    ]
